Allow renaming kitty tabs

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -187,6 +187,22 @@ alias reload_shell="exec $SHELL"
 # Reload kitty terminal
 alias reload_kitty="kill -SIGUSR1 \$(pgrep kitty)"
 
+# Set kitty tabname
+tabname() {
+  if [ "${1}" = "" ]; then
+    # If no argument given, just return
+    return 0
+  fi
+
+  if ! command -v kitten >/dev/null 2>&1; then
+    echo "kitten not found, cannot set tab title" >&2
+    return 1
+  fi
+
+  kitten @ set-tab-title "$1"
+}
+
+
 # Shrug
 alias shrug="echo '¯\_(ツ)_/¯'"
 
